CREATE DEFINER=`root`@`localhost` PROCEDURE `SCI_AW_TELINSDEL`(
   P_AFFILIATIONID       INTEGER,
   P_INSDEL              INTEGER, 
   P_TELEPHONE           VARCHAR(4000),
   X_TELEPHONE           VARCHAR(4000)    
)
BEGIN
   IF P_INSDEL = 0
   THEN
      INSERT INTO TELEPHONE (TELEPHONE_COLUMN, AFFILIATION_ID)
        VALUES   (P_TELEPHONE, P_AFFILIATIONID);
   ELSEIF P_INSDEL = 1
   THEN
      DELETE FROM   TELEPHONE
            WHERE   AFFILIATION_ID = P_AFFILIATIONID
                    AND IFNULL (TELEPHONE_COLUMN, '1xzsed6d5fe8g45bhj') =
                          IFNULL (P_TELEPHONE, '1xzsed6d5fe8g45bhj');
   ELSEIF P_INSDEL = 2
   THEN
      UPDATE   TELEPHONE
         SET   TELEPHONE_COLUMN = P_TELEPHONE
       WHERE   AFFILIATION_ID = P_AFFILIATIONID
               AND IFNULL (TELEPHONE_COLUMN, '1xzsed6d5fe8g45bhj') =
                     IFNULL (X_TELEPHONE, '1xzsed6d5fe8g45bhj');
   END IF;
      SELECT   *
        FROM   TELEPHONE
       WHERE   AFFILIATION_ID = P_AFFILIATIONID;
END