CREATE PROCEDURE `sci_op_opexist`(
	P_FUNDINGBODYID       INTEGER,
	p_taskid              INTEGER,
	p_updateflag          INTEGER,
	p_userid              INTEGER
)
BEGIN
	DECLARE v_cycle 			INTEGER;
    DECLARE L_OPPORTUNITYID   	INTEGER;

	SELECT count(OPPORTUNITYID) INTO L_OPPORTUNITYID FROM USERASSIGNMENT WHERE USERID = p_userid AND MODULEID = 3 AND ROWNUM = 1;
    
    IF p_updateflag = 0
    THEN
		IF L_OPPORTUNITYID = 0
        THEN
			SELECT WORKFLOWID, OPPORTUNITY_ID, FUNDINGBODYOPPORTUNITYID, OM.opportunityname name, op.id
            FROM OPPORTUNITY op, Opportunity_Master om, sci_workflow sw
            WHERE FUNDINGBODY_ID = P_FUNDINGBODYID AND op.OPPORTUNITY_ID = sw.id AND OM.OPPORTUNITYID= op.OPPORTUNITY_ID AND MODULEID = 3
            AND taskid = p_taskid AND sw.cycle = 0 AND Upper(trim(OPPORTUNITYSTATUS))=Upper(trim('Active')) AND IFNULL(STATUSID, 0) NOT IN (8, 7, 45)
            AND OM.STATUSCODE NOT IN (45) AND NOT EXISTS
				(SELECT 1 FROM sci_workflow WHERE ID = sw.ID AND CYCLE = sw.CYCLE AND SEQUENCE < sw.SEQUENCE AND completeddate IS NULL)
            UNION ALL
            SELECT WORKFLOWID, OPPORTUNITYID, NULL FUNDINGBODYOPPORTUNITYID, OPPORTUNITYNAME name, null id
            FROM OPPORTUNITY_master om, sci_workflow sw,OPPORTUNITY o 
            WHERE OM.OPPORTUNITYID = sw.id AND OM.OPPORTUNITYID=o.OPPORTUNITY_ID AND OM.CYCLE = sw.cycle AND sw.taskid = p_taskid 
            AND sw.MODULEID = 3 AND FUNDINGBODYID = P_FUNDINGBODYID AND isautomated = 1 AND om.cycle = 0 AND Upper(trim(o.OPPORTUNITYSTATUS))=Upper(trim('Active'))
            AND statuscode = 1 AND IFNULL(STATUSID, 0) NOT IN (7, 8, 45) AND COMPLETEDDATE IS NULL AND NOT EXISTS
				(SELECT 1 FROM OPPORTUNITY WHERE OPPORTUNITY_ID = om.OPPORTUNITYID)
			AND NOT EXISTS
				(SELECT 1 FROM sci_workflow WHERE ID = sw.ID AND CYCLE = sw.CYCLE AND SEQUENCE < sw.SEQUENCE AND completeddate IS NULL)
            ORDER BY   name;
        ELSE
			SELECT WORKFLOWID, OPPORTUNITY_ID, FUNDINGBODYOPPORTUNITYID, OM.opportunityname name, op.id
            FROM OPPORTUNITY op, Opportunity_Master om, sci_workflow sw 
            WHERE FUNDINGBODY_ID = P_FUNDINGBODYID AND op.OPPORTUNITY_ID = sw.id AND OM.OPPORTUNITYID= op.OPPORTUNITY_ID AND MODULEID = 3
            AND taskid = p_taskid AND sw.cycle = 0 AND Upper(trim(OPPORTUNITYSTATUS))=Upper(trim('Active')) AND op.OPPORTUNITY_ID IN 
				(SELECT OPPORTUNITYID FROM USERASSIGNMENT WHERE USERID = p_userid AND MODULEID = 3)
			AND IFNULL(STATUSID, 0) NOT IN (8, 7, 45) AND OM.STATUSCODE NOT IN (45) AND NOT EXISTS
				(SELECT 1 FROM sci_workflow WHERE ID = sw.ID AND CYCLE = sw.CYCLE AND SEQUENCE < sw.SEQUENCE AND completeddate IS NULL)
            UNION ALL
            SELECT WORKFLOWID, OPPORTUNITYID, NULL FUNDINGBODYOPPORTUNITYID, OPPORTUNITYNAME name, null id 
            FROM OPPORTUNITY_master om, sci_workflow sw, OPPORTUNITY o 
            WHERE OM.OPPORTUNITYID = sw.id AND OM.OPPORTUNITYID = o.OPPORTUNITY_ID AND OM.CYCLE = sw.cycle AND sw.taskid = p_taskid AND sw.MODULEID = 3 
            AND FUNDINGBODYID = P_FUNDINGBODYID AND isautomated = 1 AND om.cycle = 0 AND statuscode = 1 AND Upper(trim(o.OPPORTUNITYSTATUS))=Upper(trim('Active'))
            AND OM.OPPORTUNITYID IN 
				(SELECT OPPORTUNITYID FROM USERASSIGNMENT WHERE USERID = p_userid AND MODULEID = 3)
			AND IFNULL(STATUSID, 0) NOT IN (7, 8, 45) AND COMPLETEDDATE IS NULL AND NOT EXISTS
				(SELECT 1 FROM OPPORTUNITY WHERE OPPORTUNITY_ID = om.OPPORTUNITYID)
			AND NOT EXISTS 
				(SELECT 1 FROM sci_workflow WHERE ID = sw.ID AND CYCLE = sw.CYCLE AND SEQUENCE < sw.SEQUENCE AND completeddate IS NULL)
			ORDER BY name;
        END IF;
	END IF;
    
    IF p_updateflag = 1
    THEN
		IF L_OPPORTUNITYID = 0
        THEN
			SELECT WORKFLOWID, OPPORTUNITY_ID, FUNDINGBODYOPPORTUNITYID, OM.opportunityname name, op.id
            FROM OPPORTUNITY op, OPPORTUNITY_MASTER OM, sci_workflow sw 
            WHERE FUNDINGBODY_ID = P_FUNDINGBODYID AND op.OPPORTUNITY_ID = sw.id AND OM.OPPORTUNITYID = OP.OPPORTUNITY_ID AND MODULEID = 3 AND taskid = p_taskid AND sw.cycle > 0
            AND IFNULL(STATUSID, 0) NOT IN (8, 7, 45) AND OM.STATUSCODE NOT IN (45) AND NOT EXISTS
				(SELECT 1 FROM sci_workflow WHERE ID = sw.ID AND CYCLE = sw.CYCLE AND SEQUENCE < sw.SEQUENCE AND completeddate IS NULL)
			ORDER BY name;
        ELSE
			SELECT WORKFLOWID, OPPORTUNITY_ID, FUNDINGBODYOPPORTUNITYID, OM.opportunityname name, op.id
            FROM OPPORTUNITY op, OPPORTUNITY_MASTER OM, sci_workflow sw
            WHERE FUNDINGBODY_ID = P_FUNDINGBODYID AND op.OPPORTUNITY_ID = sw.id AND OM.OPPORTUNITYID= OP.OPPORTUNITY_ID AND MODULEID = 3 AND taskid = p_taskid  AND op.OPPORTUNITY_ID IN
				(SELECT OPPORTUNITYID FROM USERASSIGNMENT WHERE USERID = p_userid AND MODULEID = 3)
			AND sw.cycle > 0 AND IFNULL(STATUSID, 0) NOT IN (8, 7, 45) AND OM.STATUSCODE NOT IN (45) AND NOT EXISTS
				(SELECT 1 FROM sci_workflow WHERE ID = sw.ID AND CYCLE = sw.CYCLE AND SEQUENCE < sw.SEQUENCE AND completeddate IS NULL)
			ORDER BY name;
        END IF;
    END IF;
END;
