//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public string COUNTRYTEST { get; set; }
        public string ROOM { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTALCODE { get; set; }
        public Nullable<long> CONTACT_ID { get; set; }
        public Nullable<long> AWARDMANAGER_ID { get; set; }
        public Nullable<long> AFFILIATION_ID { get; set; }
        public int Id { get; set; }
    }
}
