//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class amount
    {
        public string CURRENCY { get; set; }
        public long AMOUNT_TEXT { get; set; }
        public long AWARD_ID { get; set; }
        public Nullable<long> AWARDEE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
