//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class awardfloor
    {
        public string CURRENCY { get; set; }
        public string ESTIMATEDFUNDING_TEXT { get; set; }
        public long OPPORTUNITY_ID { get; set; }
    }
}
