//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class award
    {
        public long ID { get; set; }
        public long FUNDINGBODY_ID { get; set; }
        public string FUNDINGBODYAWARDID { get; set; }
        public string TYPE { get; set; }
        public string TRUSTING { get; set; }
        public string COLLECTIONCODE { get; set; }
        public string HIDDEN { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> LASTAMENDEDDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<long> AWARD_ID { get; set; }
        public byte[] ABSTRACT { get; set; }
        public string RECORDSOURCE { get; set; }
        public Nullable<System.DateTime> AWARDNOTICEDATE { get; set; }
        public string APTARAIDENTIFIER { get; set; }
    }
}
