//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class award_tables
    {
        public string NAME { get; set; }
        public long SEQUENCE { get; set; }
        public string KEY { get; set; }
        public string PAGENAME { get; set; }
        public string MAPTABLE { get; set; }
        public long FLAG { get; set; }
    }
}
