//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class classification
    {
        public string TYPE { get; set; }
        public long CLASSIFICATIONS_ID { get; set; }
        public Nullable<long> CLASSIFICATIONGROUP_ID { get; set; }
    }
}
