//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class classification1
    {
        public long FREQUENCY { get; set; }
        public string CODE { get; set; }
        public string CLASSIFICATION_TEXT { get; set; }
        public long CLASSIFICATIONS_ID { get; set; }
    }
}
