//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactname
    {
        public string PREFIX { get; set; }
        public string GIVENNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string SURNAME { get; set; }
        public string SUFFIX { get; set; }
        public long CONTACT_ID { get; set; }
    }
}
