//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class createddate
    {
        public long VERSION { get; set; }
        public Nullable<System.DateTime> CREATEDDATE_TEXT { get; set; }
        public Nullable<long> REVISIONHISTORY_ID { get; set; }
    }
}
