//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class eligibilityclassification
    {
        public string TYPE { get; set; }
        public string ID { get; set; }
        public string ELIGIBILITYCLASSIFICATION_TEXT { get; set; }
        public Nullable<long> OPPORTUNITY_ID { get; set; }
        public Nullable<long> REGION_SPECIFIC_ID { get; set; }
        public long ELIGIBILITYCLASSIFICATION_ID { get; set; }
        public string LANG { get; set; }
    }
}
