//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class establishmentinfo
    {
        public string ESTABLISHMENTDATE { get; set; }
        public string ESTABLISHMENTCITY { get; set; }
        public string ESTABLISHMENTSTATE { get; set; }
        public string ESTABLISHMENTCOUNTRYCODE { get; set; }
        public byte[] ESTABLISHMENTDESCRIPTION { get; set; }
        public decimal FUNDINGBODY_ID { get; set; }
        public string LANG { get; set; }
    }
}
