//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class fbprogress
    {
        public long FUNDINGBODY_ID { get; set; }
        public string FUNDINGBODYNAME { get; set; }
        public Nullable<System.DateTime> FBUPDATE { get; set; }
        public string FBSTATUS { get; set; }
        public Nullable<System.DateTime> OPUPDATE { get; set; }
        public string OPSTATUS { get; set; }
        public Nullable<System.DateTime> AWUPDATE { get; set; }
        public string AWSTATUS { get; set; }
    }
}
