//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class fundedsubproject
    {
        public long SUBFUND_ID { get; set; }
        public long FUND_ID { get; set; }
        public long AWARD_ID { get; set; }
        public string FUNDINGBODYPROJECTID { get; set; }
        public Nullable<long> AMOUNT { get; set; }
        public string CURRENCY { get; set; }
    }
}
