//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class fundingbody
    {
        public long FUNDINGBODY_ID { get; set; }
        public Nullable<int> ORGDBID { get; set; }
        public string TYPE { get; set; }
        public string TRUSTING { get; set; }
        public string COUNTRY { get; set; }
        public string STATE { get; set; }
        public string COLLECTIONCODE { get; set; }
        public string HIDDEN { get; set; }
        public byte[] CANONICALNAME { get; set; }
        public byte[] PREFERREDORGNAME { get; set; }
        public byte[] CONTEXTNAME { get; set; }
        public byte[] ABBREVNAME { get; set; }
        public byte[] ELIGIBILITYDESCRIPTION { get; set; }
        public string RECORDSOURCE { get; set; }
        public Nullable<decimal> AWARDSUCCESRATE { get; set; }
        public byte[] COMMENT_DESC { get; set; }
        public string DEFUNCT { get; set; }
        public string CROSSREFID { get; set; }
        public string EXTENDEDRECORD { get; set; }
        public string CAPTUREAWARDS { get; set; }
        public string CAPTUREOPPORTUNITIES { get; set; }
        public string TIERINFO { get; set; }
        public string AWARDSSUPPLIER { get; set; }
        public string OPPORTUNITIESSUPPLIER { get; set; }
        public string AWARDSFREQUENCY { get; set; }
        public string OPPORTUNITIESFREQUENCY { get; set; }
        public string PROFIT { get; set; }
    }
}
