//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class fundedprojectdetail
    {
        public long FUND_ID { get; set; }
        public Nullable<long> AWARD_ID { get; set; }
        public string ACRONYM { get; set; }
        public Nullable<long> BUDGET_AMOUNT { get; set; }
        public string BUDGET_CURRENCY { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string FUNDINGBODYPROJECTID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public string STATUS { get; set; }
        public string COUNTRY { get; set; }
        public string LOCALITY { get; set; }
        public string POSTALCODE { get; set; }
        public string REGION { get; set; }
        public string STREET { get; set; }
        public string POSTOFFICEBOXNUMBER { get; set; }
        public string LINK { get; set; }
    }
}
