//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class installment
    {
        public long INSTALLMENTANDAMOUNT_ID { get; set; }
        public Nullable<System.DateTime> INSTALLMENTSTART_DATE { get; set; }
        public Nullable<System.DateTime> INSTALLMENTEND_DATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<long> SEQUENCE_ID { get; set; }
    }
}
