//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class keyword1
    {
        public string KEYWORD_COLUMN { get; set; }
        public long KEYWORDS_ID { get; set; }
        public string LANG { get; set; }
    }
}
