//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class link
    {
        public string URL { get; set; }
        public string LINK_TEXT { get; set; }
        public long ITEM_ID { get; set; }
        public Nullable<long> AWARDSTATISTICS_ID { get; set; }
    }
}
