//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class oppotunity
    {
        public long OPPORTUNITY_ID { get; set; }
        public string OPPORTUNITYSTATUS { get; set; }
        public long FUNDINGBODY_ID { get; set; }
        public string FUNDINGBODYOPPORTUNITYID { get; set; }
        public string LIMITEDSUBMISSION { get; set; }
        public string TRUSTING { get; set; }
        public string NEWINVESTIGATOR { get; set; }
        public string COLLECTIONCODE { get; set; }
        public string HIDDEN { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> LOIDATE { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public string ELIGIBILITYCATEGORY { get; set; }
        public string LINKTOFULLTEXT { get; set; }
        public Nullable<System.DateTime> FIRSTPOSTDATE { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDPOSTDATE { get; set; }
        public Nullable<long> NUMBEROFAWARDS { get; set; }
        public string DURATION { get; set; }
        public string LIMITEDSUBMISSIONDESCRIPTION { get; set; }
        public byte[] RAWTEXT { get; set; }
        public byte[] ELIGIBILITYDESCRIPTION { get; set; }
        public byte[] DUEDATEDESCRIPTION { get; set; }
        public Nullable<long> ID { get; set; }
        public string RECORDSOURCE { get; set; }
        public Nullable<System.DateTime> EXPIRATIONDATE { get; set; }
        public Nullable<long> DATE_FLAG { get; set; }
        public string LOI_MANDATORY { get; set; }
        public string REPEATINGOPPORTUNITY { get; set; }
        public string PREPROPOSALMANDATORY { get; set; }
        public string LANG { get; set; }
    }
}
