//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class opportunity_master
    {
        public long OPPORTUNITYID { get; set; }
        public Nullable<long> FUNDINGBODYID { get; set; }
        public string OPPORTUNITYNAME { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CYCLECOMPLETIONDATE { get; set; }
        public Nullable<long> CYCLECOMPLETEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
        public Nullable<long> LASTUPDATEDBY { get; set; }
        public Nullable<long> CYCLE { get; set; }
        public Nullable<long> STATUSCODE { get; set; }
        public Nullable<long> RUSH { get; set; }
        public Nullable<long> RUSHBY { get; set; }
        public string ALLOCATIONMODE { get; set; }
        public Nullable<long> ISAUTOMATED { get; set; }
    }
}
