//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class org
    {
        public long ORGDBID { get; set; }
        public string RELTYPE { get; set; }
        public string ORG_TEXT { get; set; }
        public Nullable<long> RELATEDORGS_ID { get; set; }
        public string LANG { get; set; }
        public Nullable<long> AFFLIATION_ID { get; set; }
    }
}
