//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicationdata
    {
        public decimal PUBLICATION_ID { get; set; }
        public Nullable<decimal> AWARD_ID { get; set; }
        public string INGESTIONID { get; set; }
        public Nullable<decimal> PUBLICATIONOUTPUTID { get; set; }
        public Nullable<System.DateTime> PUBLISHEDDATE { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public Nullable<System.DateTime> LASTUPDATEON { get; set; }
        public string PUBLICATION_AUTHOR { get; set; }
        public string JOURNAL_IDENTIFIER { get; set; }
        public string PUBLICATION_URL { get; set; }
        public string FUNDINGBODYPROJECTID { get; set; }
        public byte[] PUB_DESCRIPTION { get; set; }
        public string BULKAWID { get; set; }
    }
}
