//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class recurring
    {
        public long REC_ID { get; set; }
        public long OPPORTUNITY_ID { get; set; }
        public string RECURRING_STATUS { get; set; }
        public Nullable<long> USERID { get; set; }
        public Nullable<System.DateTime> REC_DATE { get; set; }
    }
}
