//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class relatedfundingbody
    {
        public string HIERARCHY { get; set; }
        public Nullable<long> RELEATEDFUNDINGBODIES_ID { get; set; }
        public Nullable<long> AWARD_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public long RELATEDORGSSS_ID { get; set; }
    }
}
