//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_usermaster
    {
        public long USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string NAME { get; set; }
        public string EMPCODE { get; set; }
        public string CONTACTNO { get; set; }
        public string EMAIL { get; set; }
        public string ISACTIVE { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public long CREADTEDBY { get; set; }
    }
}
