//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_related_orgs_vendor
    {
        public long REL_ORGS_VENDORID { get; set; }
        public Nullable<long> VENDOR_ID { get; set; }
        public string VENDOR_FUNDINGBODY_NAME { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
