//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_language_detail
    {
        public decimal TRAN_ID { get; set; }
        public Nullable<decimal> SCIVAL_ID { get; set; }
        public byte[] COLUMN_DESC { get; set; }
        public Nullable<decimal> COLUMN_ID { get; set; }
        public Nullable<decimal> MODULEID { get; set; }
        public Nullable<decimal> LANGUAGE_ID { get; set; }
        public Nullable<decimal> TRAN_TYPE_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
