//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_countrycodes
    {
        public long COUNTRYID { get; set; }
        public string NAME { get; set; }
        public string LCODE { get; set; }
        public string SCODE { get; set; }
        public string REGION { get; set; }
        public string SUBREGION { get; set; }
    }
}
