//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_timesheetremarks
    {
        public Nullable<long> WORKFLOWID { get; set; }
        public long TRANSITIONALID { get; set; }
        public Nullable<long> STATUSCODE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<long> USERID { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
    }
}
