//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_opp_loi_duedate_detail
    {
        public long O_ID { get; set; }
        public Nullable<long> OPPORTUNITY_ID { get; set; }
        public Nullable<System.DateTime> LOI_DUE_DATE { get; set; }
        public Nullable<int> DATE_TYPE { get; set; }
        public Nullable<long> SEQUENCE_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string DATE_REMARKS { get; set; }
        public string LANG { get; set; }
        public string URL { get; set; }
    }
}
