//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_scholarly_output
    {
        public long SCHOLARLY_ID { get; set; }
        public Nullable<long> OUTPUT_ITEM_TYPE { get; set; }
        public Nullable<long> ITEM_TYPE_TYPE { get; set; }
        public Nullable<long> RELATION_TYPE { get; set; }
        public string ITEM_TYPE_TEXT { get; set; }
        public Nullable<long> OPPORTUNITY_ID { get; set; }
        public Nullable<long> AWARD_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
