//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_groupurl
    {
        public long ID { get; set; }
        public byte[] URLID { get; set; }
        public Nullable<long> MODULEID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<long> BATCH { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
    }
}
