//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_expired_opplist
    {
        public string MODULENAME { get; set; }
        public Nullable<long> MODULEID { get; set; }
        public string OPPNAME { get; set; }
        public string FUNDINGBODYNAME { get; set; }
        public long ID { get; set; }
        public string TASKNAME { get; set; }
        public Nullable<long> TASKID { get; set; }
        public Nullable<long> CYCLE { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public Nullable<long> CID { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public string FLAG { get; set; }
    }
}
