//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_userlog
    {
        public long WORKFLOWID { get; set; }
        public Nullable<long> MODULEID { get; set; }
        public Nullable<long> ID { get; set; }
        public Nullable<long> CYCLEID { get; set; }
        public string PAGENAME { get; set; }
        public Nullable<long> USERID { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string ACTION { get; set; }
    }
}
