//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_language_master
    {
        public long LANGUAGE_ID { get; set; }
        public Nullable<long> LANGUAGE_GROUP_ID { get; set; }
        public string LANGUAGE_NAME { get; set; }
        public string LANGUAGE_CODE { get; set; }
        public Nullable<long> CODE_LENGTH { get; set; }
        public Nullable<long> PRIORITY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
