//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_urlmaster
    {
        public Nullable<long> ORGDBID { get; set; }
        public long URLID { get; set; }
        public string URL { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<long> MODULEID { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<long> RETAIN_DELETEBY { get; set; }
        public Nullable<long> LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> RETAIN_DELETEDATE { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
        public Nullable<long> BATCH { get; set; }
    }
}
