//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sci_urls
    {
        public long ID { get; set; }
        public Nullable<long> MODULEID { get; set; }
        public string PAGENAME { get; set; }
        public string URL { get; set; }
        public Nullable<long> USERID { get; set; }
        public string ISACTIVE { get; set; }
        public Nullable<long> DELETEDBY { get; set; }
    }
}
