//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class totalfunding
    {
        public string CURRENCY { get; set; }
        public long TOTALFUNDING_TEXT { get; set; }
        public Nullable<long> AWARDSTATISTICS_ID { get; set; }
    }
}
