//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracking_opp
    {
        public long TID { get; set; }
        public Nullable<long> WORKFLOWID { get; set; }
        public Nullable<long> USERID { get; set; }
        public string PAGENAME { get; set; }
        public Nullable<long> OPPORTUNITYID { get; set; }
        public Nullable<System.DateTime> TRACKINGDATE { get; set; }
        public Nullable<long> STOP_STATUS { get; set; }
    }
}
