//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class userassignment
    {
        public long AID { get; set; }
        public Nullable<long> FUNDINGBODYID { get; set; }
        public Nullable<long> MODULEID { get; set; }
        public Nullable<long> TASKID { get; set; }
        public Nullable<long> USERID { get; set; }
        public Nullable<long> ASSIGNEDBY { get; set; }
        public Nullable<System.DateTime> ASSIGNDATE { get; set; }
        public Nullable<long> CYCLE { get; set; }
        public Nullable<long> OPPORTUNITYID { get; set; }
        public Nullable<long> AWARDID { get; set; }
    }
}
