CREATE TABLE `awardceiling` (
  `CURRENCY` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `AWARDCEILING_TEXT` bigint NOT NULL,
  `OPPORTUNITY_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`AWARDCEILING_TEXT`)
);
