CREATE TABLE `awardfloor` (
  `CURRENCY` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `ESTIMATEDFUNDING_TEXT` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `OPPORTUNITY_ID` bigint NOT NULL,
  PRIMARY KEY (`CURRENCY`,`OPPORTUNITY_ID`)
);
