CREATE TABLE `award` (
  `ID` bigint NOT NULL,
  `FUNDINGBODY_ID` bigint NOT NULL,
  `FUNDINGBODYAWARDID` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `TYPE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `TRUSTING` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `COLLECTIONCODE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `HIDDEN` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `STARTDATE` date DEFAULT NULL,
  `LASTAMENDEDDATE` date DEFAULT NULL,
  `ENDDATE` date DEFAULT NULL,
  `AWARD_ID` bigint DEFAULT NULL,
  `ABSTRACT` blob,
  `RECORDSOURCE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `AWARDNOTICEDATE` date DEFAULT NULL,
  `APTARAIDENTIFIER` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
