CREATE TABLE `change` (
  `TYPE` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `POSTDATE` datetime DEFAULT NULL,
  `VERSION` bigint NOT NULL,
  `CHANGE_TEXT` varchar(4000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `CHANGEHISTORY_ID` bigint DEFAULT NULL,
  `POSTDATE_IS_SAVE` bigint DEFAULT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CHANGE_ID` bigint NOT NULL,
  PRIMARY KEY (`CHANGE_ID`)
);
