CREATE TABLE `classification` (
  `FREQUENCY` bigint NOT NULL,
  `CODE` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CLASSIFICATION_TEXT` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `CLASSIFICATIONS_ID` bigint NOT NULL,
  PRIMARY KEY (`CLASSIFICATIONS_ID`),
  KEY `IDX_CLASSIFICATION` (`CLASSIFICATIONS_ID`)
);
