CREATE TABLE `classifications` (
  `TYPE` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `CLASSIFICATIONS_ID` bigint NOT NULL,
  `CLASSIFICATIONGROUP_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`CLASSIFICATIONS_ID`),
  KEY `INX_CLASSIFICATIONS` (`CLASSIFICATIONGROUP_ID`)
);
