CREATE TABLE `createddate` (
  `VERSION` bigint NOT NULL,
  `CREATEDDATE_TEXT` datetime DEFAULT NULL,
  `REVISIONHISTORY_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`VERSION`),
  KEY `IND_SCI_CREADATE` (`REVISIONHISTORY_ID`)
);
