CREATE TABLE `eligibilityclassification` (
  `TYPE` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `ID` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `ELIGIBILITYCLASSIFICATION_TEXT` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `OPPORTUNITY_ID` bigint DEFAULT NULL,
  `REGION_SPECIFIC_ID` bigint DEFAULT NULL,
  `ELIGIBILITYCLASSIFICATION_ID` bigint NOT NULL,
  `LANG` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  PRIMARY KEY (`ELIGIBILITYCLASSIFICATION_ID`)
);
