CREATE TABLE `establishmentinfo` (
  `ESTABLISHMENTDATE` varchar(2000) DEFAULT NULL,
  `ESTABLISHMENTCITY` varchar(2000) DEFAULT NULL,
  `ESTABLISHMENTSTATE` varchar(2000) DEFAULT NULL,
  `ESTABLISHMENTCOUNTRYCODE` varchar(2000) DEFAULT NULL,
  `ESTABLISHMENTDESCRIPTION` blob,
  `FUNDINGBODY_ID` decimal(20,0) NOT NULL,
  `LANG` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`FUNDINGBODY_ID`)
);
