CREATE TABLE `estimatedamountdescription` (
  `ESTIMATEDAMOUNTDESCRIPTION_ID` bigint NOT NULL,
  `OPPORTUNITY_ID` bigint DEFAULT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ESTIMATEDAMOUNTDESCRIPTION_ID`)
);
