CREATE TABLE `fundingbodyamount` (
  `AMOUNT` decimal(20,2) NOT NULL,
  `CURRENCY` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `RELEATEDFUNDINGBODIES_ID` bigint NOT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`RELEATEDFUNDINGBODIES_ID`,`AMOUNT`)
);
