CREATE TABLE `installment` (
  `INSTALLMENTANDAMOUNT_ID` bigint NOT NULL,
  `INSTALLMENTSTART_DATE` datetime DEFAULT NULL,
  `INSTALLMENTEND_DATE` datetime DEFAULT NULL,
  `AMOUNT` decimal(10,2) DEFAULT NULL,
  `CURRENCY` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `CREATED_DATE` datetime DEFAULT NULL,
  `SEQUENCE_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`INSTALLMENTANDAMOUNT_ID`)
);
