CREATE TABLE `item` (
  `RELTYPE` varchar(2000) DEFAULT NULL,
  `DESCRIPTION` blob,
  `ITEM_ID` decimal(20,0) NOT NULL,
  `GEOSCOPE_ID` decimal(20,0) DEFAULT NULL,
  `APPINFO_ID` decimal(20,0) DEFAULT NULL,
  `ABOUT_ID` decimal(20,0) DEFAULT NULL,
  `RELATEDITEMS_ID` decimal(20,0) DEFAULT NULL,
  `SYNOPSIS_ID` decimal(20,0) DEFAULT NULL,
  `SUBJECTMATTER_ID` decimal(20,0) DEFAULT NULL,
  `LANG` varchar(50) DEFAULT NULL,
  `FUNDINGPOLICY_ID` decimal(20,0) DEFAULT NULL,
  `ELIGIBILITYDESCRIPTION_ID` decimal(20,0) DEFAULT NULL,
  `ESTIMATEDAMOUNTDESCRIPTION_ID` decimal(20,0) DEFAULT NULL,
  `LIMITEDSUBMISSIONDESC_ID` decimal(20,0) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ITEM_ID`)
);
