CREATE TABLE `opportunity_master` (
  `OPPORTUNITYID` bigint NOT NULL,
  `FUNDINGBODYID` bigint DEFAULT NULL,
  `OPPORTUNITYNAME` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `URL` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `CREATEDDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATEDBY` bigint DEFAULT NULL,
  `CYCLECOMPLETIONDATE` datetime DEFAULT NULL,
  `CYCLECOMPLETEDBY` bigint DEFAULT NULL,
  `LASTUPDATEDDATE` datetime DEFAULT NULL,
  `LASTUPDATEDBY` bigint DEFAULT NULL,
  `CYCLE` bigint DEFAULT NULL,
  `STATUSCODE` bigint DEFAULT NULL,
  `RUSH` bigint DEFAULT NULL,
  `RUSHBY` bigint DEFAULT NULL,
  `ALLOCATIONMODE` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `ISAUTOMATED` bigint DEFAULT NULL,
  PRIMARY KEY (`OPPORTUNITYID`)
);
