CREATE TABLE `publicationdata` (
  `PUBLICATION_ID` decimal(20,0) NOT NULL,
  `AWARD_ID` decimal(20,0) DEFAULT NULL,
  `INGESTIONID` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `PUBLICATIONOUTPUTID` decimal(20,0) DEFAULT NULL,
  `PUBLISHEDDATE` date DEFAULT NULL,
  `CREATEDON` date DEFAULT NULL,
  `LASTUPDATEON` datetime DEFAULT CURRENT_TIMESTAMP,
  `PUBLICATION_AUTHOR` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `JOURNAL_IDENTIFIER` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `PUBLICATION_URL` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `FUNDINGBODYPROJECTID` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `PUB_DESCRIPTION` blob,
  `BULKAWID` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`PUBLICATION_ID`)
);
