CREATE TABLE `relatedorgs` (
  `HIERARCHY` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `RELATEDORGS_ID` bigint NOT NULL,
  `FUNDINGBODY_ID` bigint DEFAULT NULL,
  `AWARD_ID` bigint DEFAULT NULL,
  `OPPORTUNITY_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`RELATEDORGS_ID`),
  KEY `IND_SCI_RELATEDORGS` (`AWARD_ID`)
);
