CREATE TABLE `relatedfundingbodies` (
  `HIERARCHY` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `RELEATEDFUNDINGBODIES_ID` bigint DEFAULT NULL,
  `AWARD_ID` bigint DEFAULT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `RELATEDORGSSS_ID` bigint NOT NULL,
  PRIMARY KEY (`RELATEDORGSSS_ID`)
);
