CREATE TABLE `relateditems` (
  `RELATEDITEMS_ID` bigint NOT NULL,
  `FUNDINGBODY_ID` bigint DEFAULT NULL,
  `OPPORTUNITY_ID` bigint DEFAULT NULL,
  `AWARD_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`RELATEDITEMS_ID`)
);
