CREATE TABLE `relatedprograms` (
  `HIERARCHY` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `RELATEDPROGRAMS_ID` bigint NOT NULL,
  `OPPORTUNITY_ID` bigint DEFAULT NULL,
  `AWARD_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`RELATEDPROGRAMS_ID`)
);
