CREATE TABLE `researchoutcome` (
  `RESEARCHOUTCOME_ID` bigint NOT NULL,
  `AWARD_ID` bigint DEFAULT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`RESEARCHOUTCOME_ID`)
);
