CREATE TABLE `revisionhistory` (
  `STATUS` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `REVISIONHISTORY_ID` bigint NOT NULL,
  `FUNDINGBODY_ID` bigint DEFAULT NULL,
  `OPPORTUNITY_ID` bigint DEFAULT NULL,
  `AWARD_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`REVISIONHISTORY_ID`),
  KEY `IND_SCI_REVHIST` (`AWARD_ID`)
);
