CREATE TABLE `sci_urlmaster` (
  `ORGDBID` bigint DEFAULT NULL,
  `URLID` bigint NOT NULL,
  `URL` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `STATUS` bigint DEFAULT NULL,
  `MODULEID` bigint DEFAULT NULL,
  `CREATEDBY` bigint DEFAULT NULL,
  `RETAIN_DELETEBY` bigint DEFAULT NULL,
  `LASTUPDATEDBY` bigint DEFAULT NULL,
  `CREATEDDATE` datetime DEFAULT NULL,
  `RETAIN_DELETEDATE` datetime DEFAULT NULL,
  `LASTUPDATEDDATE` datetime DEFAULT NULL,
  `BATCH` bigint DEFAULT NULL,
  PRIMARY KEY (`URLID`),
  KEY `IND_SCI_URLMASTER` (`ORGDBID`),
  KEY `IND_SCI_URLMST1` (`STATUS`)
);
