CREATE TABLE `sci_timesheet` (
  `TRANSITIONALID` bigint NOT NULL,
  `WORKFLOWID` bigint DEFAULT NULL,
  `MODULEID` bigint DEFAULT NULL,
  `ID` bigint DEFAULT NULL,
  `TASKID` bigint DEFAULT NULL,
  `USERID` bigint DEFAULT NULL,
  `CYCLEID` bigint DEFAULT NULL,
  `STATUSCODE` bigint DEFAULT NULL,
  `STARTDATE` datetime DEFAULT NULL,
  `ENDDATE` datetime DEFAULT NULL,
  `IDLETIME` bigint DEFAULT NULL,
  `ISERROR` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  PRIMARY KEY (`TRANSITIONALID`)
);
