CREATE TABLE `sci_scholarly_output` (
  `SCHOLARLY_ID` bigint NOT NULL,
  `OUTPUT_ITEM_TYPE` bigint DEFAULT NULL,
  `ITEM_TYPE_TYPE` bigint DEFAULT NULL,
  `RELATION_TYPE` bigint DEFAULT NULL,
  `ITEM_TYPE_TEXT` varchar(3000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `OPPORTUNITY_ID` bigint DEFAULT NULL,
  `AWARD_ID` bigint DEFAULT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SCHOLARLY_ID`)
);
