CREATE TABLE `sci_related_orgs_vendor` (
  `REL_ORGS_VENDORID` bigint NOT NULL,
  `VENDOR_ID` bigint DEFAULT NULL,
  `VENDOR_FUNDINGBODY_NAME` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `CREATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`REL_ORGS_VENDORID`),
  UNIQUE KEY `VENDOR_ID_UK` (`VENDOR_ID`)
);
