CREATE TABLE `subtype` (
  `ID` bigint NOT NULL,
  `SUBTYPE_TEXT` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `FUNDINGBODY_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SUBTYPE_U01` (`FUNDINGBODY_ID`)
);
