CREATE TABLE `totalamount` (
  `INSTALLMENTANDAMOUNT_ID` bigint NOT NULL,
  `AMOUNT` decimal(20,2) DEFAULT NULL,
  `CURRENCY` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`INSTALLMENTANDAMOUNT_ID`)
);
