CREATE TABLE `tracking_fb` (
  `TID` bigint NOT NULL,
  `WORKFLOWID` bigint DEFAULT NULL,
  `USERID` bigint DEFAULT NULL,
  `PAGENAME` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '',
  `FUNDINGBODYID` bigint DEFAULT NULL,
  `TRACKINGDATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `STOP_STATUS` bigint DEFAULT NULL,
  PRIMARY KEY (`TID`)
);
