CREATE TABLE `tracking_log` (
  `TLOGID` bigint NOT NULL,
  `MODULEID` bigint DEFAULT NULL,
  `TASKID` bigint DEFAULT NULL,
  `SEQUENCE` bigint DEFAULT NULL,
  `STARTDATE` datetime DEFAULT NULL,
  `STARTBY` bigint DEFAULT NULL,
  `COMPLETEDDATE` datetime DEFAULT NULL,
  `COMPLETEDBY` bigint DEFAULT NULL,
  `STATUSID` bigint DEFAULT NULL,
  PRIMARY KEY (`TLOGID`)
);
