CREATE TABLE `userassignment` (
  `AID` bigint NOT NULL,
  `FUNDINGBODYID` bigint DEFAULT NULL,
  `MODULEID` bigint DEFAULT NULL,
  `TASKID` bigint DEFAULT NULL,
  `USERID` bigint DEFAULT NULL,
  `ASSIGNEDBY` bigint DEFAULT NULL,
  `ASSIGNDATE` datetime DEFAULT NULL,
  `CYCLE` bigint DEFAULT NULL,
  `OPPORTUNITYID` bigint DEFAULT NULL,
  `AWARDID` bigint DEFAULT NULL,
  PRIMARY KEY (`AID`)
);
