CREATE DEFINER=`root`@`localhost` PROCEDURE `SCI_CLASSIFICATIONUPDEL`(
	P_WORKFLOWID                INTEGER,
	P_INSDEL                    INTEGER,                
	P_TYPE                      VARCHAR(4000),
	P_FREQUENCY                 INTEGER,
	P_CODE                      VARCHAR(4000),
	P_CLASSIFICATION_TEXT       VARCHAR(4000),
	P_CLASSIFICATIONS_ID        VARCHAR(4000),
	O_FREQUENCY                 INTEGER,
	O_CODE                      VARCHAR(4000)
)
BEGIN
	DECLARE V_CLASSIFICATIONS       INTEGER;
	DECLARE V_CLASSIFICATIONGROUP   INTEGER;
	DECLARE V_FUNDINGBODYID         INTEGER;
	DECLARE V_MODULEID              INTEGER;

	BEGIN

		INSERT INTO frog
		VALUES   (
		CONCAT('0 FREQUENCY'
		, '*** '
		, IFNULL(O_FREQUENCY, '')
		, '---- '
		, 'CODE'
		, '*** '
		, IFNULL(O_CODE, '')
		, '---- '
		, 'CLASSIFICATIONS_ID'
		, '*** '
		, IFNULL(P_CLASSIFICATIONS_ID, '')
		, '*** '
		, 'FREQUENCY'
		, '---- '
		, IFNULL(P_FREQUENCY, '')
		, '*** '
		, 'code'
		, '---- '
		, IFNULL(P_CODE, '')
		, '---- '
		, IFNULL(P_CLASSIFICATION_TEXT, '')),
		SYSDATE()
		);

		SELECT   ID, MODULEID
		INTO   V_FUNDINGBODYID, V_MODULEID
		FROM   SCI_WORKFLOW
		WHERE   WORKFLOWID = P_WORKFLOWID;

		IF V_MODULEID = 2
		THEN

			IF P_INSDEL = 1
			THEN
				DELETE FROM   CLASSIFICATION WHERE   FREQUENCY = P_FREQUENCY
				AND IFNULL (CODE, '1x2jf432dsf') =
				 IFNULL (P_CODE, '1x2jf432dsf')
				AND IFNULL (CLASSIFICATION_TEXT, '1x2jf432dsf') =
				 IFNULL (P_CLASSIFICATION_TEXT, '1x2jf432dsf')
				AND CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;

				SELECT   COUNT(*) INTO   V_CLASSIFICATIONS FROM   CLASSIFICATION WHERE   CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;

				IF V_CLASSIFICATIONS = 0
				THEN
					DELETE FROM   CLASSIFICATIONS WHERE   CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;
				END IF;

				SELECT   COUNT(*) INTO   V_CLASSIFICATIONGROUP FROM   CLASSIFICATIONS
				WHERE   CLASSIFICATIONGROUP_ID =
				(SELECT   CLASSIFICATIONGROUP_ID FROM   CLASSIFICATIONGROUP WHERE   FUNDINGBODY_ID = V_FUNDINGBODYID);

				IF V_CLASSIFICATIONGROUP = 0
				THEN
					DELETE FROM   CLASSIFICATIONGROUP WHERE   FUNDINGBODY_ID = V_FUNDINGBODYID;
				END IF;

			ELSEIF P_INSDEL = 2
			THEN
				UPDATE   CLASSIFICATION SET   FREQUENCY = P_FREQUENCY, CODE = P_CODE, CLASSIFICATION_TEXT = P_CLASSIFICATION_TEXT
				WHERE       CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID AND FREQUENCY = O_FREQUENCY AND CODE = O_CODE;

				UPDATE   CLASSIFICATIONS SET   TYPE = P_TYPE WHERE   CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;

				INSERT INTO frog
				VALUES   (
				CONCAT('2 FREQUENCY'
				, '*** '
				, IFNULL(O_FREQUENCY, '')
				, '---- '
				, 'CODE'
				, '*** '
				, IFNULL(O_CODE, '')
				, '---- '
				, 'CLASSIFICATIONS_ID'
				, '*** '
				, IFNULL(P_CLASSIFICATIONS_ID, '')),
				SYSDATE()
				);				

				SELECT   CGP.CLASSIFICATIONGROUP_ID,
				CGP.FUNDINGBODY_ID,
				CFS.TYPE,
				CFS.CLASSIFICATIONS_ID,
				CF.FREQUENCY,
				CF.CODE,
				CF.CLASSIFICATION_TEXT
				FROM CLASSIFICATIONGROUP CGP
				LEFT JOIN CLASSIFICATIONS CFS
				ON CGP.CLASSIFICATIONGROUP_ID = CFS.CLASSIFICATIONGROUP_ID
				LEFT JOIN CLASSIFICATION CF
				ON CFS.CLASSIFICATIONS_ID = CF.CLASSIFICATIONS_ID
				WHERE CGP.FUNDINGBODY_ID = V_FUNDINGBODYID;
				
			END IF;

		ELSEIF V_MODULEID = 3
		THEN

			IF P_INSDEL = 1
			THEN
				DELETE FROM   CLASSIFICATION WHERE   FREQUENCY = P_FREQUENCY
					AND IFNULL (CODE, '1X2VRE98JHNDGC') =
					 IFNULL (P_CODE, '1X2VRE98JHNDGC')
					AND IFNULL (CLASSIFICATION_TEXT, '1X2VRE98JHNDGC') =
					 IFNULL (P_CLASSIFICATION_TEXT, '1X2VRE98JHNDGC')
					AND CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;

				SELECT   COUNT(*) INTO   V_CLASSIFICATIONS FROM   CLASSIFICATION WHERE   CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;

				IF V_CLASSIFICATIONS = 0
				THEN
					DELETE FROM   CLASSIFICATIONS WHERE   CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;
				END IF;

				SELECT   COUNT(*) INTO   V_CLASSIFICATIONGROUP FROM CLASSIFICATIONS WHERE CLASSIFICATIONGROUP_ID =
				(SELECT   CLASSIFICATIONGROUP_ID FROM   CLASSIFICATIONGROUP WHERE   OPPORTUNITY_ID = V_FUNDINGBODYID);

				IF V_CLASSIFICATIONGROUP = 0
				THEN
					DELETE FROM   CLASSIFICATIONGROUP WHERE   OPPORTUNITY_ID = V_FUNDINGBODYID;
				END IF;

			ELSEIF P_INSDEL = 2
			THEN
				UPDATE CLASSIFICATION SET   FREQUENCY = P_FREQUENCY, CODE = P_CODE,
					CLASSIFICATION_TEXT = P_CLASSIFICATION_TEXT,
					CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID
				WHERE CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID AND FREQUENCY = O_FREQUENCY AND CODE = O_CODE;

				INSERT INTO frog
				VALUES   (
				CONCAT(' 3 FREQUENCY'
				, '*** '
				, IFNULL(O_FREQUENCY, '')
				, '---- '
				, 'CODE'
				, '*** '
				, IFNULL(O_CODE, '')
				, '---- '
				, 'CLASSIFICATIONS_ID'
				, '*** '
				, IFNULL(P_CLASSIFICATIONS_ID, '')),
				SYSDATE()
				);

				UPDATE   CLASSIFICATIONS SET   TYPE = P_TYPE WHERE   CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;

				SELECT   CGP.CLASSIFICATIONGROUP_ID,
				CGP.FUNDINGBODY_ID,
				CFS.TYPE,
				CFS.CLASSIFICATIONS_ID,
				CF.FREQUENCY,
				CF.CODE,
				CF.CLASSIFICATION_TEXT
				FROM   CLASSIFICATIONGROUP CGP
				LEFT JOIN CLASSIFICATIONS CFS
				ON CGP.CLASSIFICATIONGROUP_ID = CFS.CLASSIFICATIONGROUP_ID
				LEFT JOIN CLASSIFICATION CF
				ON CFS.CLASSIFICATIONS_ID = CF.CLASSIFICATIONS_ID
				WHERE CGP.OPPORTUNITY_ID = V_FUNDINGBODYID;
				
			END IF;

		ELSEIF V_MODULEID = 4
		THEN

			IF P_INSDEL = 1
			THEN
					DELETE FROM   CLASSIFICATION WHERE       FREQUENCY = P_FREQUENCY AND CODE = P_CODE
						AND CLASSIFICATION_TEXT = P_CLASSIFICATION_TEXT
						AND CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;

					SELECT   COUNT(*) INTO   V_CLASSIFICATIONS FROM   CLASSIFICATION
					WHERE   CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;

				IF V_CLASSIFICATIONS = 0
				THEN
					DELETE FROM   CLASSIFICATIONS WHERE   CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;
				END IF;

				SELECT COUNT(*) INTO V_CLASSIFICATIONGROUP FROM CLASSIFICATIONS WHERE CLASSIFICATIONGROUP_ID 
				IN (SELECT CLASSIFICATIONGROUP_ID FROM CLASSIFICATIONGROUP WHERE AWARD_ID = V_FUNDINGBODYID);

				IF V_CLASSIFICATIONGROUP = 0
				THEN
					DELETE FROM   CLASSIFICATIONGROUP WHERE   AWARD_ID = V_FUNDINGBODYID
					AND NOT EXISTS
					(SELECT   1
					   FROM   CLASSIFICATIONS
					  WHERE   CLASSIFICATIONGROUP_ID =
								 X.CLASSIFICATIONGROUP_ID);
				END IF;

			ELSEIF P_INSDEL = 2
			THEN
				UPDATE CLASSIFICATION SET FREQUENCY = P_FREQUENCY,CODE = P_CODE,
					CLASSIFICATION_TEXT = P_CLASSIFICATION_TEXT,
					CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID
				WHERE CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID
				AND FREQUENCY = O_FREQUENCY
				AND CODE = O_CODE;

				INSERT INTO frog
				VALUES   (
				CONCAT(' 4 FREQUENCY'
				, '*** '
				, IFNULL(O_FREQUENCY, '')
				, '---- '
				, 'CODE'
				, '*** '
				, IFNULL(O_CODE, '')
				, '---- '
				, 'CLASSIFICATIONS_ID'
				, '*** '
				, IFNULL(P_CLASSIFICATIONS_ID, '')),
				SYSDATE()
				);

				UPDATE CLASSIFICATIONS SET TYPE = P_TYPE WHERE CLASSIFICATIONS_ID = P_CLASSIFICATIONS_ID;

				SELECT CGP.CLASSIFICATIONGROUP_ID,
				CGP.FUNDINGBODY_ID,
				CFS.TYPE,
				CFS.CLASSIFICATIONS_ID,
				CF.FREQUENCY,
				CF.CODE,
				CF.CLASSIFICATION_TEXT
				FROM   CLASSIFICATIONGROUP CGP
				LEFT JOIN CLASSIFICATIONS CFS
				ON CGP.CLASSIFICATIONGROUP_ID = CFS.CLASSIFICATIONGROUP_ID
				LEFT JOIN CLASSIFICATION CF
				ON CFS.CLASSIFICATIONS_ID = CF.CLASSIFICATIONS_ID
				WHERE CGP.AWARD_ID = V_FUNDINGBODYID;

				if V_MODULEID=2
				then

					SELECT   CGP.CLASSIFICATIONGROUP_ID,
					CGP.FUNDINGBODY_ID,
					CFS.TYPE,
					CFS.CLASSIFICATIONS_ID,
					CF.FREQUENCY,
					CF.CODE,
					CF.CLASSIFICATION_TEXT
					FROM   CLASSIFICATIONGROUP CGP
					LEFT JOIN CLASSIFICATIONS CFS
					ON CGP.CLASSIFICATIONGROUP_ID = CFS.CLASSIFICATIONGROUP_ID
					LEFT JOIN CLASSIFICATION CF
					ON CFS.CLASSIFICATIONS_ID = CF.CLASSIFICATIONS_ID
					WHERE CGP.FUNDINGBODY_ID = V_FUNDINGBODYID;

				elseif V_MODULEID=3
				then

					SELECT   CGP.CLASSIFICATIONGROUP_ID,
					CGP.FUNDINGBODY_ID,
					CFS.TYPE,
					CFS.CLASSIFICATIONS_ID,
					CF.FREQUENCY,
					CF.CODE,
					CF.CLASSIFICATION_TEXT
					FROM   CLASSIFICATIONGROUP CGP
					LEFT JOIN CLASSIFICATIONS CFS
					ON CGP.CLASSIFICATIONGROUP_ID = CFS.CLASSIFICATIONGROUP_ID
					LEFT JOIN CLASSIFICATION CF
					ON CFS.CLASSIFICATIONS_ID = CF.CLASSIFICATIONS_ID
					WHERE CGP.OPPORTUNITY_ID = V_FUNDINGBODYID;

				elseif  V_MODULEID=4
				then

					SELECT   CGP.CLASSIFICATIONGROUP_ID,
					CGP.FUNDINGBODY_ID,
					CFS.TYPE,
					CFS.CLASSIFICATIONS_ID,
					CF.FREQUENCY,
					CF.CODE,
					CF.CLASSIFICATION_TEXT
					FROM   CLASSIFICATIONGROUP CGP
					LEFT JOIN CLASSIFICATIONS CFS
					ON CGP.CLASSIFICATIONGROUP_ID = CFS.CLASSIFICATIONGROUP_ID
					LEFT JOIN CLASSIFICATION CF
					ON CFS.CLASSIFICATIONS_ID = CF.CLASSIFICATIONS_ID
					WHERE CGP.AWARD_ID = V_FUNDINGBODYID;
				end if;

			END IF;
		END IF;			
	END;
END ;;
