CREATE PROCEDURE `sci_proc_backtask`(
	P_USERID         INTEGER,
	P_ID             INTEGER,
	P_moduleid       INTEGER,
	P_taskid         INTEGER,
	P_CYCLE          INTEGER
)
SP: BEGIN
	IF P_taskid = 7
	THEN
		DELETE FROM sci_workflow WHERE moduleid = P_moduleid AND id = P_ID AND taskid = 7;
		COMMIT;
		LEAVE SP;
	END IF;
   
	IF P_moduleid = 2
	THEN
		UPDATE SCI_WORKFLOW SET STARTDATE = NULL, STARTBY = NULL, STATUSID = NULL
		WHERE STARTBY = P_USERID AND MODULEID = P_moduleid AND ID = P_ID AND CYCLE = P_CYCLE AND TASKID = P_taskid AND ASSIGNBY IS NULL;
    
		IF ROW_COUNT() = 0
			THEN
				UPDATE SCI_WORKFLOW SET STARTDATE = NULL, STARTBY = NULL, STATUSID = 9
				WHERE STARTBY = P_USERID AND MODULEID = P_moduleid AND ID = P_ID AND CYCLE = P_CYCLE AND TASKID = P_taskid AND ASSIGNBY IS NOT NULL;
		END IF;
	ELSE
		UPDATE SCI_WORKFLOW SET STARTDATE = NULL, STARTBY = NULL, STATUSID = NULL
		WHERE STARTBY = P_USERID AND WORKFLOWID = P_ID AND ASSIGNBY IS NULL;

		IF ROW_COUNT() = 0
		THEN
			UPDATE SCI_WORKFLOW SET STARTDATE = NULL, STARTBY = NULL, STATUSID = 9
            WHERE STARTBY = P_USERID AND WORKFLOWID = P_ID AND ASSIGNBY IS NOT NULL;
		END IF;
	END IF;

	COMMIT;
END;
